export const products = [
  {
    id: "PRD-001",
    name: "กาแฟสดคั่วบด",
    category: "เครื่องดื่ม",
    stock: 38,
    unit: "แพ็ค",
    reorderPoint: 25,
    price: 280,
  },
  {
    id: "PRD-002",
    name: "นมอัลมอนด์",
    category: "เครื่องดื่ม",
    stock: 18,
    unit: "ลัง",
    reorderPoint: 15,
    price: 420,
  },
  {
    id: "PRD-003",
    name: "ไซรัปวนิลา",
    category: "ส่วนผสม",
    stock: 9,
    unit: "ขวด",
    reorderPoint: 12,
    price: 150,
  },
  {
    id: "PRD-004",
    name: "แก้วกระดาษ 16oz",
    category: "บรรจุภัณฑ์",
    stock: 520,
    unit: "ชิ้น",
    reorderPoint: 400,
    price: 3.5,
  },
  {
    id: "PRD-005",
    name: "ฝาปิดแก้ว 16oz",
    category: "บรรจุภัณฑ์",
    stock: 410,
    unit: "ชิ้น",
    reorderPoint: 350,
    price: 2.5,
  },
  {
    id: "PRD-006",
    name: "เค้กส้มสไลซ์",
    category: "เบเกอรี่",
    stock: 26,
    unit: "ชิ้น",
    reorderPoint: 20,
    price: 55,
  },
  {
    id: "PRD-007",
    name: "มัฟฟินช็อกโกแลต",
    category: "เบเกอรี่",
    stock: 14,
    unit: "ชิ้น",
    reorderPoint: 18,
    price: 45,
  },
  {
    id: "PRD-008",
    name: "ซองกาแฟดริป",
    category: "บรรจุภัณฑ์",
    stock: 120,
    unit: "ชิ้น",
    reorderPoint: 100,
    price: 2,
  },
  {
    id: "PRD-009",
    name: "คุกกี้เนยสด",
    category: "เบเกอรี่",
    stock: 32,
    unit: "แพ็ค",
    reorderPoint: 28,
    price: 80,
  },
  {
    id: "PRD-010",
    name: "ไซรัปคาราเมล",
    category: "ส่วนผสม",
    stock: 12,
    unit: "ขวด",
    reorderPoint: 15,
    price: 185,
  },
];
